version: "2"

run:
  concurrency: 4

linters:
  enable:
  - gocritic
  - gosec
  - revive
  exclusions:
    generated: lax
    rules:
      - linters:
        - revive
        path: pkg/provider/gardener/ruleset/disak8sstig/rules/
        text: 'exported: exported'
      - linters:
        - revive
        path: pkg/provider/managedk8s/ruleset/disak8sstig/rules/
        text: 'exported: exported'
      - linters:
        - revive
        path: pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/
        text: 'exported: exported'
      - linters:
        - revive
        path: pkg/provider/virtualgarden/ruleset/disak8sstig/rules/
        text: 'exported: exported'
      - linters:
        - revive
        path: pkg/provider/garden/ruleset/securityhardenedshoot/rules/
        text: 'exported: exported'
      - linters:
        - revive
        path: pkg/shared/ruleset/disak8sstig/rules/
        text: 'exported: exported'
  settings:
    revive:
      rules:
      # recommended rules https://github.com/mgechev/revive/tree/v1.9.0?tab=readme-ov-file#recommended-configuration
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
        arguments:
        - allowedPackages:
          - github.com/onsi/ginkgo/v2
          - github.com/onsi/gomega
          - github.com/onsi/gomega/gstruct
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
        arguments:
        - disableStutteringCheck
      - name: increment-decrement
      - name: var-naming
        # var-naming arguments are ordered https://github.com/mgechev/revive/blob/v1.11.0/RULES_DESCRIPTIONS.md#var-naming
        arguments:
        - []
        - []
        -
          - skipPackageNameChecks: true
      - name: var-declaration
      # - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      # - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
