version: "2"

run:
  concurrency: 4

linters:
  enable:
    - gocritic
    - gosec
    - revive
  exclusions:
    generated: lax
    rules:
      - linters:
          - revive
        path: pkg/provider/gardener/ruleset/disak8sstig/rules/
        text: 'exported: exported'
      - linters:
          - revive
        path: pkg/provider/managedk8s/ruleset/disak8sstig/rules/
        text: 'exported: exported'
      - linters:
          - revive
        path: pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/
        text: 'exported: exported'
      - linters:
          - revive
        path: pkg/provider/virtualgarden/ruleset/disak8sstig/rules/
        text: 'exported: exported'
      - linters:
          - revive
        path: pkg/provider/garden/ruleset/securityhardenedshoot/rules/
        text: 'exported: exported'
      - linters:
          - revive
        path: pkg/shared/ruleset/disak8sstig/rules/
        text: 'exported: exported'
      # - path: (.+)\.go$
      #   text: var-naming # ((var|const|struct field|func) .* should be .*
      - path: (.+)\.go$
        text: dot-imports # should not use dot imports
      - path: (.+)\.go$
        text: 'exported: (type|func) name will be used as .* by other packages, and that stutters;'
      - path: (.+)\.go$
        text: indent-error-flow # if block ends with a return statement, so drop this else and outdent its block
      - path: (.+)\.go$
        text: package-comments
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
