apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: diki:garden-access
rules:
- apiGroups:
  - core.gardener.cloud
  resources:
  - cloudprofiles
  - namespacedcloudprofiles
  - shoots
  verbs:
  - get
