apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: diki:managedk8s-access
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  verbs:
  - create
  - delete
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - nodes
  - nodes/proxy
  - namespaces
  - pods
  - replicationcontrollers
  - services
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - replicasets
  - statefulsets
  verbs:
  - get
  - list
- apiGroups:
  - batch
  resources:
  - jobs
  - cronjobs   
  verbs:
  - get
  - list
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - get
  - list
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - get
  - list
- apiGroups:
  - rbac.authorization.k8s.io 
  resources:
  - roles
  - clusterroles
  verbs:
  - get
  - list
