#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

"$(dirname $0)"/../vendor/github.com/gardener/gardener/hack/.ci/set_dependency_version
