name: Release
on:
  workflow_dispatch:
    inputs:
      next-version:
        type: choice
        options:
          - bump-minor
          - bump-patch


jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      mode: release
    permissions:
      contents: write
      packages: write
      id-token: write

  release-to-github-and-bump:
    uses: gardener/cc-utils/.github/workflows/release.yaml@master
    needs:
      - build
    permissions:
      contents: write
      packages: write
      id-token: write
    secrets: inherit
    with:
      release-commit-target: branch
      next-version: ${{ inputs.next-version }}
      next-version-callback-action-path:
      slack-channel-id: C9CEBQPGE # #sap-tech-gardener
      assets: |
        - name: diki-darwin-amd64
          type: ocm-resource
          id:
            name: diki
            os: darwin
            architecture: amd64
        - name: diki-darwin-arm64
          type: ocm-resource
          id:
            name: diki
            os: darwin
            architecture: arm64
        - name: diki-linux-amd64
          type: ocm-resource
          id:
            name: diki
            os: linux
            architecture: amd64
        - name: diki-linux-arm64
          type: ocm-resource
          id:
            name: diki
            os: linux
            architecture: arm64
        - name: diki-windows-amd64.exe
          type: ocm-resource
          id:
            name: diki
            os: windows
            architecture: amd64

  publish-to-package-repositories:
    permissions:
      contents: write
      actions:  read
    needs:
      - release-to-github-and-bump
    secrets: inherit
    uses: ./.github/workflows/publish-to-package-repositories.yaml
    with:
      component-descriptor: ${{ needs.release-to-github-and-bump.outputs.component-descriptor }}
